---
# Playbook: system_preparation.yml
# Purpose: Update system packages and disable swap
# Compatible with Ubuntu 24.04 nodes

- name: System preparation - Update packages and disable swap
  hosts: k8s_cluster
  gather_facts: true
  any_errors_fatal: true
  
  tasks:
    # Update package repositories and upgrade packages
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
      
    - name: Upgrade all packages
      apt:
        upgrade: full
        autoremove: yes
        autoclean: yes
      register: apt_upgrade_result
        
    - name: Show package upgrade summary
      debug:
        msg: "{{ apt_upgrade_result.stdout_lines | default(['No upgrades performed']) }}"
      when: apt_upgrade_result.stdout_lines is defined
    
    # Disable swap permanently
    - name: Check if swap is enabled
      command: swapon --show
      register: swap_status
      changed_when: false

    - name: Disable swap immediately
      command: swapoff -a
      when: swap_status.stdout != ""
      
    - name: Remove swap entries from /etc/fstab
      replace:
        path: /etc/fstab
        regexp: '^([^#].*\sswap\s+sw\s+.*)$'
        replace: '# \1'
        backup: yes
      register: fstab_change
      
    - name: Check if systemd-swap service exists
      command: systemctl list-unit-files systemd-swap.service
      register: systemd_swap_check
      failed_when: false
      changed_when: false
      
    - name: Disable systemd-swap if it exists
      systemd:
        name: systemd-swap
        enabled: no
        state: stopped
      when: systemd_swap_check.rc == 0 and 'systemd-swap.service' in systemd_swap_check.stdout

    - name: Configure swappiness to zero
      sysctl:
        name: vm.swappiness
        value: '0'
        state: present
        reload: yes
      
    - name: Verify swap is disabled
      command: swapon --show
      register: verify_swap
      changed_when: false
      
    - name: Show swap status
      debug:
        msg: "Swap status: {{ 'Disabled' if verify_swap.stdout == '' else 'Still enabled!' }}"

    # Reboot if needed (optional, commented out by default)
    - name: Check if reboot is required
      stat:
        path: /var/run/reboot-required
      register: reboot_required

    - name: Notify if reboot is required
      debug:
        msg: "Reboot is required. Consider rebooting the system."
      when: reboot_required.stat.exists

    # Uncomment the following block if you want to enable automatic reboots
    # - name: Reboot system if needed
    #   reboot:
    #     msg: "Rebooting after system updates and swap disabling"
    #     connect_timeout: 5
    #     reboot_timeout: 300
    #     post_reboot_delay: 30
    #   when: reboot_required.stat.exists or fstab_change.changed