apiVersion: security-profiles-operator.x-k8s.io/v1alpha1
kind: AppArmorProfile
metadata:
  name: nginx-profile
spec:
  policy: |
    #include <tunables/global>
    profile nginx-profile flags=(attach_disconnected) {
      file,
      network,
      capability,
      /usr/sbin/nginx rix,
      deny /bin/su mr,
    }
    
