apiVersion: v1
kind: Pod
metadata:
  name: nginx-secured
spec:
  containers:
    - name: nginx
      image: nginx
      securityContext:
        appArmorProfile: nginx-profile
      ports:
        - containerPort: 80
