---
# Simple playbook to update and upgrade all hosts
# Run with: ansible-playbook -i inventory/nodes.ini apt-update-upgrade.yaml

- name: Update and upgrade all hosts
  hosts: all
  become: true
  gather_facts: true
  
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
      
    - name: Upgrade all packages
      apt:
        upgrade: yes
        update_cache: no
        cache_valid_time: 3600
        autoremove: yes
      register: upgrade_result
      
    - name: Show upgrade results
      debug:
        msg: "{{ upgrade_result.stdout_lines | default(['No changes made']) }}"
      when: upgrade_result.stdout_lines is defined
      
    - name: Show if system requires a reboot
      stat:
        path: /var/run/reboot-required
      register: reboot_required
      
    - name: Notify if reboot is required
      debug:
        msg: "System requires a reboot"
      when: reboot_required.stat.exists
