---
# Playbook to safely reboot all hosts in the inventory
# Usage: ansible-playbook -i nodes.ini reboot-hosts.yaml

- name: Reboot all hosts in the inventory
  hosts: all
  gather_facts: true
  become: true
  any_errors_fatal: false
  
  tasks:
    - name: Get hostname before reboot
      command: hostname
      register: hostname_before
      changed_when: false

    - name: Get uptime before reboot
      shell: cat /proc/uptime | awk '{print $1}'
      register: uptime_before
      changed_when: false

    - name: Display pre-reboot information
      debug:
        msg: 
          - "Host: {{ hostname_before.stdout }}"
          - "IP: {{ ansible_host }}"
          - "Uptime: {{ uptime_before.stdout | float | int }} seconds"
          - "Preparing to reboot..."

    - name: Reboot the server
      reboot:
        msg: "Reboot initiated by Ansible"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 5
        post_reboot_delay: 30
        test_command: whoami

    - name: Get hostname after reboot
      command: hostname
      register: hostname_after
      changed_when: false

    - name: Get uptime after reboot
      shell: cat /proc/uptime | awk '{print $1}'
      register: uptime_after
      changed_when: false

    - name: Verify the reboot was successful
      debug:
        msg: 
          - "Host: {{ hostname_after.stdout }}"
          - "IP: {{ ansible_host }}"
          - "New uptime: {{ uptime_after.stdout | float | int }} seconds"
          - "Reboot completed successfully!"
      when: uptime_after.stdout | float < uptime_before.stdout | float