---
- name: Check and Install gVisor via Official Repository
  hosts: k8s_cluster
  become: true
  gather_facts: true

  tasks:
    - name: Check if CPU supports user namespaces (required by gVisor)
      ansible.builtin.command: sysctl kernel.unprivileged_userns_clone
      register: userns_clone
      failed_when: false
      changed_when: false

    - name: Fail if user namespaces not enabled
      ansible.builtin.fail:
        msg: "System not compatible with gVisor: 'kernel.unprivileged_userns_clone' is not enabled."
      when: userns_clone.stdout.find("= 1") == -1

    - name: Install required dependencies
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
        state: present
        update_cache: true

    - name: Add gVisor GPG key
      ansible.builtin.shell: |
        curl -fsSL https://gvisor.dev/archive.key | gpg --dearmor -o /usr/share/keyrings/gvisor-archive-keyring.gpg
      args:
        creates: /usr/share/keyrings/gvisor-archive-keyring.gpg

    - name: Add gVisor repository to APT sources
      ansible.builtin.copy:
        dest: /etc/apt/sources.list.d/gvisor.list
        content: |
          deb [arch={{ ansible_architecture | lower }} signed-by=/usr/share/keyrings/gvisor-archive-keyring.gpg] https://storage.googleapis.com/gvisor/releases release main
        mode: '0644'

    - name: Update apt package lists
      ansible.builtin.apt:
        update_cache: yes

    - name: Install runsc (gVisor runtime)
      ansible.builtin.apt:
        name: runsc
        state: present

    - name: Remove old runsc binary from /usr/local/bin if exists
      ansible.builtin.file:
        path: /usr/local/bin/runsc
        state: absent

    - name: Verify correct runsc version is available
      ansible.builtin.command: /usr/bin/runsc --version
      register: runsc_version
      changed_when: false

    - name: Print correct runsc version
      ansible.builtin.debug:
        msg: "gVisor installed successfully and using: {{ runsc_version.stdout }}"
