apiVersion: v1
kind: Pod
metadata:
  name: default-capabilities-pod
spec:
  containers:
    - name: busybox
      image: busybox
      command: ["sleep", "3600"]
---
apiVersion: v1
kind: Pod
metadata:
  name: dropped-capabilities-pod
spec:
  containers:
    - name: busybox
      image: busybox
      command: ["sleep", "3600"]
      securityContext:
        capabilities:
          drop:
            - NET_RAW
            - SYS_ADMIN
