apiVersion: v1
kind: Pod
metadata:
  name: pod-level-security-context
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 3000
    fsGroup: 2000
  containers:
    - name: busybox
      image: busybox
      command: ["sleep", "3600"]

