---
# deploy-docker-config.yaml
# Usage: ansible-playbook deploy-docker-config.yaml
# Installs Docker Engine on Ubuntu hosts using the official Docker install script

- name: Install Docker Engine on Ubuntu using official script
  hosts: all
  become: true
  gather_facts: true

  vars:
    docker_install_script_url: https://get.docker.com
    docker_install_script_path: /tmp/install-docker.sh
    docker_config_file: /etc/docker/daemon.json
    docker_config_content: |
      {
        "log-driver": "json-file",
        "log-opts": {
          "max-size": "100m"
        },
        "storage-driver": "overlay2"
      }

  tasks:
    - name: Download Docker install script
      get_url:
        url: "{{ docker_install_script_url }}"
        dest: "{{ docker_install_script_path }}"
        mode: '0755'

    - name: Run Docker install script
      command: sh {{ docker_install_script_path }}
      args:
        creates: /usr/bin/docker

    - name: Ensure Docker service is started and enabled
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Create Docker config directory
      file:
        path: /etc/docker
        state: directory
        mode: '0755'

    - name: Deploy Docker daemon.json config
      copy:
        dest: "{{ docker_config_file }}"
        content: "{{ docker_config_content }}"
        mode: '0644'
      notify: Restart Docker

    - name: Add current user to docker group (optional)
      user:
        name: "{{ ansible_user | default('ubuntu') }}"
        groups: docker
        append: yes
      when: ansible_user is defined

  handlers:
    - name: Restart Docker
      systemd:
        name: docker
        state: restarted
